[workspace]
dependencies_update = true
changelog_update = false
pr_labels = ["release"]

[[package]]
name = "marco-test-one"
semver_check = false
changelog_update = true
changelog_path = "./CHANGELOG.md"

[[package]]
name = "marco-test-two"
changelog_update = true
