[workspace]
git_release_latest = false

[[package]] # the double square brackets define a TOML table array
name = "marco-test-two" # name of the package to configure
changelog_include = ["marco-test-one"] # include commits from `release_plz_core` in the changelog
