[workspace]
# disable the changelog for all packages
changelog_update = false

[[package]] # the double square brackets define a TOML table array
name = "marco-test-two" # name of the package to configure
changelog_update = true
changelog_path = "./CHANGELOG.md"
changelog_include = ["marco-test-one", "marco-test-three"]

[changelog]
body = """
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}

### `{{package}}`
{% for group, commits in commits | group_by(attribute="group") %}
#### {{ group | upper_first }}
{% for commit in commits %}
{%- if commit.scope -%}
- *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{%- if commit.links %} ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%}){% endif %}
{% else -%}
- {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}
{% endif -%}
{% endfor -%}
{% endfor %}
"""
