[workspace]

[[package]] # the double square brackets define a TOML table array
name = "marco-test-two" # name of the package to configure
changelog_include = ["marco-test-one"] # include commits from `release_plz_core` in the changelog
version_group = "aa"

[[package]]
name = "marco-test-one"
git_release_enable = false
version_group = "aa"
