[workspace]
git_release_body = """
{{ changelog }}
{% if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
* @{{ contributor.username }}
{% endfor %}
{% endif %}
"""

[[package]] # the double square brackets define a TOML table array
name = "marco-test-two" # name of the package to configure

[[package]]
name = "marco-test-one"
