[package]
name = "one"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "0.8"
anyhow = "1.0.52"
tokio = "1"
tonic = "0.6"
lapin = "1"
