name: Cargo Assist

permissions:
  contents: write

on:
  push:

jobs:
  cargo-assist:
    name: Cargo assist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CARGO_FMT_BOT_TOKEN }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cargo assist
        uses: MarcoIeni/cargo-assist@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          working_directory: subdir
