name: Cargo fmt bot

permissions:
  contents: write

on:
  push:

jobs:
  cargo-fmt-bot:
    name: Cargo fmt bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CARGO_FMT_BOT_TOKEN }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Configure git user from GitHub token
        uses: MarcoIeni/git-config@v0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Fix formatting and clippy
        shell: bash
        run: |
          cargo clippy --fix
          cargo fmt --all

          # If repository has uncommitted changes, commit them
          if [[ -n $(git status -s) ]]
          then
              git add .
              git commit -m "cargo fmt and clippy fixes"
              git push
          fi
