name: Cargo fmt bot

permissions:
  contents: write

on:
  push:

jobs:
  cargo-fmt-bot:
    name: Cargo fmt bot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Run Cargo fmt bot
        uses: MarcoIeni/cargo-fmt-bot@main
        env:
          GITHUB_TOKEN: ${{ secrets.CARGO_FMT_BOT_TOKEN }}
