name: Release-plz

on:
  push:
    branches:
      - main

jobs:

  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run release-plz
        uses: MarcoIeni/release-plz-action@debug2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
