name: CI # Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  zizmor:
    name: Zizmor
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: Run zizmor
        uses: marcoieni/zizmor-action@e998bb7d659f55728f2bff86f10956544e375063
        with:
          persona: pedantic
          # Don't use GitHub advanced security.
          # Instead, fail if there's a security issue.
          advanced-security: false
